config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/OSTrails/FDP-Index-Proxy:
      branch: master
      repo: https://github.com/OSTrails/FDP-Index-Proxy.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/OSTrails/FDP-Index-Proxy git:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-black-wildebeest.sh
        container: qc.acc_wheezy-blue-woodpecker
  QC.Doc:
    repos:
      github.com/OSTrails/FDP-Index-Proxy find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-zucchini-pig.sh
        container: qc.doc_cranky-lemon-wolf
      github.com/OSTrails/FDP-Index-Proxy git:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-magnolia-terrier.sh
        container: qc.doc_gloppy-pink-bison
      github.com/OSTrails/FDP-Index-Proxy markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-smalt-fox.sh
        container: qc.doc_sleazy-goldenrod-jackal
  QC.Lic:
    repos:
      github.com/OSTrails/FDP-Index-Proxy licensee:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-yellow-wasp.sh
        container: qc.lic_frumpy-alizarin-macaque
  QC.Sty:
    repos:
      github.com/OSTrails/FDP-Index-Proxy hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-brass-rabbit.sh
        container: qc.sty_boozy-buff-cheetah
      github.com/OSTrails/FDP-Index-Proxy rubocop:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-cyan-caracal.sh
        container: qc.sty_woozy-violet-anteater
  QC.Ver:
    repos:
      github.com/OSTrails/FDP-Index-Proxy get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-peach-chow.sh
        container: qc.ver_slimy-chocolate-wallaby
timeout: 5400
